### ISSUE TITLE
Missing #if-defs for non-debug builds in ThreadedMailBox.cc

### ISSUE THREAD

**Issue by vollkorn1982** [couchbaselabs/BLIP-Cpp#14]
When trying to compile this project with clang on Linux I received errors about undefined `_active`, which makes sense because in `src/util/ThreadedMailbox.hh` the definition is like this:
```
#if DEBUG
        std::atomic_int _active {0};
#endif
```
But in `src/util/ThreadedMailbox.cc` the variable `_active` is not guarded by #if-defs.
```
    void ThreadedMailbox::performNextMessage() {
        LogToAt(ActorLog, Verbose, "%s performNextMessage", _actor->actorName().c_str());
        DebugAssert(++_active == 1);     // Fail-safe check to detect 'impossible' re-entrant call
        sCurrentActor = _actor;
        auto &fn = front();
        fn();
        sCurrentActor = nullptr;
        
        DebugAssert(--_active == 0);
```
Therefore if `DEBUG` is false clang fails compiling this code.

My proposed fix:
```
% git diff
diff --git a/src/util/ThreadedMailbox.cc b/src/util/ThreadedMailbox.cc
index c81aa0e..7ccc5ef 100644
--- a/src/util/ThreadedMailbox.cc
+++ b/src/util/ThreadedMailbox.cc
@@ -200,13 +200,17 @@ namespace litecore { namespace actor {
 
     void ThreadedMailbox::performNextMessage() {
         LogToAt(ActorLog, Verbose, "%s performNextMessage", _actor->actorName().c_str());
+#if DEBUG
         DebugAssert(++_active == 1);     // Fail-safe check to detect 'impossible' re-entrant call
+#endif
         sCurrentActor = _actor;
         auto &fn = front();
         fn();
         sCurrentActor = nullptr;
         
+#if DEBUG
         DebugAssert(--_active == 0);
+#endif
 
         bool empty;
         popNoWaiting(empty);
```

**Comment by borrrden** [comment]
`DebugAssert` is a no-op in non-debug builds so `_active` should not be compiled there either.

**Comment by vollkorn1982** [comment]
Don't wanna argue about the C/C++ language here with you, but, well, clang is doing something different than what you expect :)

I assume gcc works fine. Maybe a compiler-specific problem? But I don't care to invest much time into researching this further, since it can be fixed very easily and IMHO cleanly. Do you see any negative side effects of these additional #ifdefs why they shouldn't be included?

**Comment by borrrden** [comment]
We actually compile *only* with clang and not gcc on Linux.  I'd like to see how you arrive at this point of compile failure and how it differs from what we are doing.

**Comment by vollkorn1982** [comment]
Unfortunately, I forgot why I even tried compiling this project. It was as a dependency of another project which I needed for one 5-day job in March. Maybe the Makefile, which was cloning and compiling this project, had some funny way to compile it.

Anyway, since you don't want to fix this without seeing what exactly my compiler did and I'm not able to reproduce it, I close this issue.
